[workspace]
resolver = "2"
members = ["core/options", "core/ime-bridge", "core/ime-policy", "core/ime-ipc", "core/clipboard", "core/sync", "core/skin", "platforms/windows", "platforms/windows-host", "platforms/windows-algo", "platforms/windows-ipc", "platforms/windows-skin", "platforms/windows-settings", "platforms/relay", "platforms/android/rimejni"]

[workspace.package]
edition = "2021"
license = "GPL-3.0"
