package com.shurufa.ime

/**
 * M-A2-2 表情面板数据（搜狗安卓 8.0 表情面板 / 4.8 表情搜索）。
 * 数据与 PC 设置中心符号面板同源（windows-settings/ui/src/main.js），
 * 由 scripts/gen-emoji-panel.py 生成，保证双端分类/搜索一致。
 */
data class EmojiCategory(val id: String, val label: String, val symbols: List<String>)

object EmojiPanel {
    val CATEGORIES: List<EmojiCategory> = listOf(
        EmojiCategory("face", "表情", listOf(
            "😀",
            "😁",
            "😂",
            "🤣",
            "😊",
            "😇",
            "🙂",
            "😉",
            "😍",
            "😘",
            "😗",
            "😋",
            "😛",
            "😜",
            "🤪",
            "😝",
            "🤗",
            "🤭",
            "🤫",
            "🤔",
            "🤨",
            "😐",
            "😶",
            "😏",
            "😒",
            "🙄",
            "😌",
            "😔",
            "😪",
            "🤤",
            "😴",
            "😷",
            "🤒",
            "🤕",
            "🤢",
            "🤮",
            "🤧",
            "🥵",
            "🥶",
            "🥴",
            "😵",
            "🤯",
            "🤠",
            "🥳",
            "😎",
            "🤓",
            "🧐",
            "😕",
            "😟",
            "🙁",
            "😮",
            "😯",
            "😲",
            "😳",
            "🥺",
            "😢",
            "😭",
            "😱",
            "😖",
            "😣",
            "😤",
            "😡",
            "😠",
            "🤬",
            "😈",
            "👿",
            "💀",
            "💩",
            "🤡",
            "👻",
            "👽",
            "🤖",
            "🎃",
        )),
        EmojiCategory("hand", "手势", listOf(
            "👍",
            "👎",
            "👏",
            "🙏",
            "💪",
            "✋",
            "🤙",
            "👌",
            "🤝",
            "🙌",
            "👐",
            "🤲",
            "👊",
            "✊",
            "🤛",
            "🤜",
            "☝",
            "✌",
            "🤞",
            "🤟",
            "🤘",
            "👈",
            "👉",
            "👆",
            "👇",
            "🫰",
            "🫶",
            "✍",
            "🖐",
            "👋",
        )),
        EmojiCategory("animal", "动物", listOf(
            "🐶",
            "🐱",
            "🐭",
            "🐹",
            "🐰",
            "🦊",
            "🐻",
            "🐼",
            "🐨",
            "🐯",
            "🦁",
            "🐮",
            "🐷",
            "🐸",
            "🐵",
            "🐔",
            "🐧",
            "🐦",
            "🦆",
            "🦅",
            "🦉",
            "🐺",
            "🐗",
            "🐴",
            "🦄",
            "🐝",
            "🐛",
            "🦋",
            "🐌",
            "🐞",
            "🐢",
            "🐍",
            "🦎",
            "🐙",
            "🦑",
            "🦐",
            "🦀",
            "🐠",
            "🐟",
            "🐬",
            "🐳",
            "🦈",
            "🦓",
            "🦍",
            "🐘",
            "🦒",
            "🐕",
            "🐈",
        )),
        EmojiCategory("life", "生活", listOf(
            "🍎",
            "🍊",
            "🍋",
            "🍌",
            "🍉",
            "🍇",
            "🍓",
            "🍑",
            "🍍",
            "🥝",
            "🍅",
            "🥑",
            "🥕",
            "🌽",
            "🍞",
            "🥐",
            "🧀",
            "🍖",
            "🍔",
            "🍟",
            "🍕",
            "🌮",
            "🥗",
            "🍲",
            "☕",
            "🍵",
            "🧋",
            "🍺",
            "🍷",
            "🥂",
            "🍰",
            "🎂",
            "🍦",
            "🍿",
            "🏠",
            "🏡",
            "🏢",
            "🏥",
            "🏫",
            "🏪",
            "🏔",
            "🌋",
            "🗻",
            "🌊",
            "🏖",
            "⛺",
            "🚗",
            "🚕",
            "🚌",
            "🚲",
            "✈",
            "🚀",
            "🚢",
            "🚉",
            "🚦",
            "⛽",
            "⚽",
            "🏀",
            "🏈",
            "⚾",
            "🎾",
            "🏐",
            "🏓",
            "🏸",
            "⛳",
            "🏹",
            "🎣",
            "🎿",
            "🏊",
            "🚴",
            "🏋",
            "🎮",
            "🎲",
            "🎯",
            "🎨",
            "🎬",
            "🎤",
            "🎧",
            "🎹",
            "🎸",
            "🎺",
            "🥁",
            "🎻",
            "📱",
            "💻",
            "⌨",
            "🖥",
            "📷",
            "🎥",
            "📺",
            "📻",
            "⏰",
            "📅",
            "📌",
            "📎",
            "✂",
            "🔑",
            "🔒",
            "🔓",
            "💡",
            "🔋",
            "💰",
            "💎",
            "🎁",
            "🎈",
            "🎉",
            "🎊",
            "🏆",
            "🥇",
            "🥈",
            "🥉",
            "🛒",
            "🛍",
            "🧸",
        )),
        EmojiCategory("heart", "爱心", listOf(
            "❤",
            "🧡",
            "💛",
            "💚",
            "💙",
            "💜",
            "🖤",
            "🤍",
            "🤎",
            "💔",
            "❣",
            "💕",
            "💞",
            "💓",
            "💗",
            "💖",
            "💘",
            "💝",
            "💟",
            "💌",
            "💢",
            "💤",
            "💦",
            "✨",
            "⭐",
            "🌟",
            "💫",
            "🔥",
            "💥",
            "🌈",
            "☀",
            "☁",
            "⛅",
            "🌙",
            "☔",
            "❄",
            "⚡",
        )),
        EmojiCategory("kaomoji", "颜文字", listOf(
            "(◕‿◕)",
            "(≧∇≦)ﾉ",
            "(´･ω･`)",
            "(￣▽￣)~*",
            "(∩´∀`)∩",
            "＼(^o^)／",
            "( ͡° ͜ʖ ͡°)",
            "¯\\_(ツ)_/¯",
            "(╯°□°)╯︵ ┻━┻",
            "┬─┬ ノ( ゜-゜ノ)",
            "(ノಠ益ಠ)ノ彡┻━┻",
            "(ﾉ>ω<)ﾉ",
            "(｡•̀ᴗ-)✧",
            "(づ｡◕‿‿◕｡)づ",
            "(◣_◢)",
            "(´▽`ʃ♡ƪ)",
            "(≧◡≦)",
            "(｡◕‿◕｡)",
            "(ง •̀_•́)ง",
            "ᕙ(⇀‸↼‶)ᕗ",
            "(๑•̀ㅂ•́)و✧",
            "( •̀ᴗ•́ )و",
            "✧(≖ ◡ ≖✿)",
            "(°ロ°)!",
        )),
    )

    /** [中文名, 拼音, 英文名, emoji]；与 PC 端搜索索引同源。 */
    val SEARCH_INDEX: List<List<String>> = listOf(
        listOf("微笑", "weixiao", "smile", "😊"),
        listOf("大笑", "daxiao", "laugh", "😂"),
        listOf("笑哭", "xiaoku", "joy", "🤣"),
        listOf("开心", "kaixin", "happy", "😄"),
        listOf("喜欢", "xihuan", "love", "😍"),
        listOf("亲吻", "qinwen", "kiss", "😘"),
        listOf("调皮", "tiaopi", "playful", "😜"),
        listOf("酷", "ku", "cool", "😎"),
        listOf("思考", "sikao", "think", "🤔"),
        listOf("哭", "ku", "cry", "😭"),
        listOf("生气", "shengqi", "angry", "😡"),
        listOf("困", "kun", "sleepy", "😴"),
        listOf("生病", "shengbing", "sick", "🤒"),
        listOf("恶心", "exin", "vomit", "🤢"),
        listOf("震惊", "zhenjing", "shock", "😱"),
        listOf("晕", "yun", "dizzy", "😵"),
        listOf("魔鬼", "mogui", "devil", "😈"),
        listOf("骷髅", "kugu", "skull", "💀"),
        listOf("鬼", "gui", "ghost", "👻"),
        listOf("外星人", "waixingren", "alien", "👽"),
        listOf("机器人", "jiqiren", "robot", "🤖"),
        listOf("赞", "zan", "thumbsup", "👍"),
        listOf("踩", "cai", "thumbsdown", "👎"),
        listOf("鼓掌", "guzhang", "clap", "👏"),
        listOf("祈祷", "qidao", "pray", "🙏"),
        listOf("谢谢", "xiexie", "thanks", "🙏"),
        listOf("感恩", "ganen", "grateful", "🙏"),
        listOf("肌肉", "jirou", "muscle", "💪"),
        listOf("挥手", "huishou", "wave", "👋"),
        listOf("拳头", "quantou", "fist", "👊"),
        listOf("击掌", "jizhang", "highfive", "🙌"),
        listOf("比心", "bixin", "heart", "🫶"),
        listOf("抱拳", "baoquan", "folded", "🤝"),
        listOf("握手", "woshou", "handshake", "🤝"),
        listOf("耶", "ye", "victory", "✌"),
        listOf("狗", "gou", "dog", "🐶"),
        listOf("猫", "mao", "cat", "🐱"),
        listOf("老鼠", "laoshu", "mouse", "🐭"),
        listOf("兔子", "tuzi", "rabbit", "🐰"),
        listOf("狐狸", "huli", "fox", "🦊"),
        listOf("熊", "xiong", "bear", "🐻"),
        listOf("熊猫", "xiongmao", "panda", "🐼"),
        listOf("老虎", "laohu", "tiger", "🐯"),
        listOf("狮子", "shizi", "lion", "🦁"),
        listOf("牛", "niu", "cow", "🐮"),
        listOf("猪", "zhu", "pig", "🐷"),
        listOf("青蛙", "qingwa", "frog", "🐸"),
        listOf("猴子", "houzi", "monkey", "🐵"),
        listOf("鸡", "ji", "chicken", "🐔"),
        listOf("企鹅", "qie", "penguin", "🐧"),
        listOf("蝴蝶", "hudie", "butterfly", "🦋"),
        listOf("蜜蜂", "mifeng", "bee", "🐝"),
        listOf("乌龟", "wugui", "turtle", "🐢"),
        listOf("蛇", "she", "snake", "🐍"),
        listOf("章鱼", "zhangyu", "octopus", "🐙"),
        listOf("鱼", "yu", "fish", "🐟"),
        listOf("鲸鱼", "jingyu", "whale", "🐳"),
        listOf("鲨鱼", "shayu", "shark", "🦈"),
        listOf("大象", "daxiang", "elephant", "🐘"),
        listOf("苹果", "pingguo", "apple", "🍎"),
        listOf("橘子", "juzi", "orange", "🍊"),
        listOf("柠檬", "ningmeng", "lemon", "🍋"),
        listOf("香蕉", "xiangjiao", "banana", "🍌"),
        listOf("西瓜", "xigua", "watermelon", "🍉"),
        listOf("葡萄", "putao", "grape", "🍇"),
        listOf("草莓", "caomei", "strawberry", "🍓"),
        listOf("桃", "tao", "peach", "🍑"),
        listOf("菠萝", "boluo", "pineapple", "🍍"),
        listOf("番茄", "fanqie", "tomato", "🍅"),
        listOf("牛油果", "niuyouguo", "avocado", "🥑"),
        listOf("玉米", "yumi", "corn", "🌽"),
        listOf("面包", "mianbao", "bread", "🍞"),
        listOf("奶酪", "nailao", "cheese", "🧀"),
        listOf("汉堡", "hanbao", "burger", "🍔"),
        listOf("薯条", "shutiao", "fries", "🍟"),
        listOf("披萨", "pisa", "pizza", "🍕"),
        listOf("沙拉", "shala", "salad", "🥗"),
        listOf("火锅", "huoguo", "hotpot", "🍲"),
        listOf("咖啡", "kafei", "coffee", "☕"),
        listOf("茶", "cha", "tea", "🍵"),
        listOf("啤酒", "pijiu", "beer", "🍺"),
        listOf("蛋糕", "dangao", "cake", "🎂"),
        listOf("冰淇淋", "bingqilin", "icecream", "🍦"),
        listOf("心", "xin", "heart", "❤"),
        listOf("红心", "hongxin", "redheart", "❤"),
        listOf("爱心", "aixin", "loveheart", "💕"),
        listOf("破碎", "posui", "broken", "💔"),
        listOf("火花", "huohua", "fire", "🔥"),
        listOf("星星", "xingxing", "star", "⭐"),
        listOf("彩虹", "caihong", "rainbow", "🌈"),
        listOf("闪电", "shandian", "bolt", "⚡"),
        listOf("雪", "xue", "snow", "❄"),
        listOf("太阳", "taiyang", "sun", "☀"),
        listOf("月亮", "yueliang", "moon", "🌙"),
        listOf("雨", "yu", "rain", "☔"),
        listOf("房子", "fangzi", "house", "🏠"),
        listOf("车", "che", "car", "🚗"),
        listOf("飞机", "feiji", "plane", "✈"),
        listOf("火箭", "huojian", "rocket", "🚀"),
        listOf("轮船", "lunchuan", "ship", "🚢"),
        listOf("足球", "zuqiu", "soccer", "⚽"),
        listOf("篮球", "lanqiu", "basketball", "🏀"),
        listOf("乒乓球", "pingpang", "tabletennis", "🏓"),
        listOf("游戏", "youxi", "game", "🎮"),
        listOf("骰子", "touzi", "dice", "🎲"),
        listOf("音乐", "yinyue", "music", "🎵"),
        listOf("吉他", "jita", "guitar", "🎸"),
        listOf("相机", "xiangji", "camera", "📷"),
        listOf("电话", "dianhua", "phone", "📱"),
        listOf("电脑", "diannao", "computer", "💻"),
        listOf("钱", "qian", "money", "💰"),
        listOf("钻石", "zuanshi", "diamond", "💎"),
        listOf("礼物", "liwu", "gift", "🎁"),
        listOf("气球", "qiqiu", "balloon", "🎈"),
        listOf("奖杯", "jiangbei", "trophy", "🏆"),
        listOf("金币", "jinbi", "medal", "🥇"),
        listOf("购物", "gouwu", "shopping", "🛒"),
        listOf("玩具熊", "wanjuxiong", "teddy", "🧸"),
        listOf("蜡烛", "lazhu", "candle", "🕯"),
    )

    /** 面板内搜索：关键词索引命中优先，其次符号字符/分类名包含，去重保序。 */
    fun search(query: String): List<String> {
        val q = query.trim().lowercase()
        if (q.isEmpty()) return emptyList()
        val hits = mutableListOf<String>()
        val seen = mutableSetOf<String>()
        fun push(s: String) { if (seen.add(s)) hits.add(s) }
        for (entry in SEARCH_INDEX) {
            if (entry.dropLast(1).any { it.lowercase().contains(q) }) push(entry.last())
        }
        for (cat in CATEGORIES) {
            val labelHit = cat.label.lowercase().contains(q)
            for (s in cat.symbols) {
                if (labelHit || s.lowercase().contains(q)) push(s)
            }
        }
        return hits
    }

    // 最近使用：分隔符串持久化，最多保留 limit 条，重复上移。
    const val RECENT_KEY = "emoji_recent"
    fun decodeRecent(raw: String): List<String> =
        raw.split("\u0001").filter { it.isNotBlank() }
    fun encodeRecent(list: List<String>): String = list.joinToString("\u0001")
    fun pushRecent(current: List<String>, emoji: String, limit: Int = 30): List<String> =
        (listOf(emoji) + current.filter { it != emoji }).take(limit)
}
